# Generated by Django 3.2.13 on 2022-04-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='превью'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='видео'),
        ),
    ]
