# Generated by Django 3.2.13 on 2022-04-21 18:15

from django.db import migrations, models
import market.models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20220421_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='extra_fields',
            field=models.JSONField(blank=True, null=True, verbose_name='дополнительные поля'),
        ),
        migrations.AddField(
            model_name='lot',
            name='extra_fields',
            field=models.JSONField(blank=True, null=True, verbose_name='дополнительные поля'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=market.models.image_rename, verbose_name='превью'),
        ),
    ]
