# Generated by Django 3.2.13 on 2022-04-22 12:02

from django.db import migrations, models
import django.db.models.deletion
import treewidget.fields


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20220421_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='category',
            field=treewidget.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='price',
            field=models.FloatField(verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='title',
            field=models.CharField(max_length=150, verbose_name='заголовок'),
        ),
    ]
