# Generated by Django 3.2.13 on 2022-04-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_lot_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.JSONField(verbose_name='')),
            ],
            options={
                'verbose_name': 'набор дополнительных полей',
                'verbose_name_plural': 'наборы дополнительных полей',
            },
        ),
    ]
