# Generated by Django 3.2.13 on 2022-04-24 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_extrafield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='extra_fields',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.extrafield', verbose_name='дополнительные поля'),
        ),
        migrations.AlterField(
            model_name='extrafield',
            name='description',
            field=models.JSONField(verbose_name='описание набора'),
        ),
    ]
