# Generated by Django 3.2.13 on 2022-04-26 07:24

from django.db import migrations
import market.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20220424_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'галерея', 'verbose_name_plural': 'галереи'},
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=market.models.image_rename, verbose_name='изображение'),
        ),
    ]
