# Generated by Django 3.2.13 on 2022-04-27 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_auto_20220426_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lot',
            options={'ordering': ['-created_at'], 'verbose_name': 'объявление', 'verbose_name_plural': 'объявления'},
        ),
    ]
