# Generated by Django 3.2.13 on 2022-04-27 20:02

from django.db import migrations, models
import personal.models
import phonenumber_field.modelfields
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=30, verbose_name='наименование')),
                ('status', models.CharField(max_length=20, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'местоположение',
                'verbose_name_plural': 'местоположения',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user'], 'verbose_name': 'профиль пользователя', 'verbose_name_plural': 'профили пользователя'},
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=personal.models.image_rename, verbose_name='аватар'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='номер телефона'),
        ),
    ]
